# golangci-lint config
linters-settings:
  lll:
    line-length: 180
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"

